-- CreateTable
CREATE TABLE "Project" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "m2" INTEGER NOT NULL,
    "gg" REAL NOT NULL DEFAULT 4.5,
    "start" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "ProductionRatePoint" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "date" DATETIME NOT NULL,
    "rate" REAL NOT NULL
);
